name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          only-new-issues: true

      - name: Build
        run: go build -v ./...

    # Uncomment the following lines to include the test step
    # - name: Test
    #   run: go test -v ./...
